AllCops:
    NewCops: enable
    Exclude:
        - 'db/schema.rb'
        - 'vendor/**/*'

Layout/LineLength:
    Max: 150

Style/Documentation:
    Exclude:
        - 'app/helpers/application_helper.rb'
        - 'app/mailers/application_mailer.rb'
        - 'app/models/application_record.rb'
        - 'config/application.rb'
        - 'test/application_system_test_case.rb'
        - 'test/test_helper.rb'

Style/MixinUsage:
    Exclude:
        - 'bin/setup'
        - 'bin/update'

Style/ClassAndModuleChildren:
    Exclude:
        - 'test/test_helper.rb'
